# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        #width, height
        self.window_size = (1920, 1080)
        self.status_size = int(0.05 * self.window_size[0])
        self.button_text_size = int(0.5 * self.status_size)
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(self.window_size[0], self.window_size[1])
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        #The spacing area at the top between window bar and plotting figure
        # spacerItem = QtWidgets.QSpacerItem(self.window_size[1], #width
        #                                    int(0.01 * self.window_size[1]), #height
        #                                    QtWidgets.QSizePolicy.Expanding, 
        #                                    QtWidgets.QSizePolicy.Minimum)
        
        spacerItem = QtWidgets.QSpacerItem(MainWindow.width(), #width
                                    int(0.01 * MainWindow.height()), #height
                                    QtWidgets.QSizePolicy.Expanding, 
                                    QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.groupBox.setObjectName("groupBox")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.setObjectName("gridLayout")
        
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        ###
        self.label_6.setStyleSheet(f''' font-size: {self.status_size}px; color: Red;''')
        self.label_6.setIndent(60)
        ###
        
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        
        self.verticalLayout.addLayout(self.gridLayout)
        
        self.gridLayout_4.addWidget(self.groupBox, 3, 1, 1, 1)
        
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout1.setObjectName("verticalLayout1")
        
        self.buttonsLayout = QtWidgets.QVBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        ###
        #Left, above, right, under
        # self.buttonsLayout.setContentsMargins(120, 500, 120, 0)
        self.buttonsLayout.setContentsMargins(int(0.1 * self.window_size[0]), int(0.5 * self.window_size[1]), int(0.1 * self.window_size[0]), 0)
        ###
        
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        self.startButton = QtWidgets.QPushButton(self.groupBox1)
        self.startButton.setObjectName("startButton")
        ###
        self.startButton.setStyleSheet(f'background-color: #555555; font-size: {self.button_text_size}px; color: white;')
        ###

        self.gridLayout_6.addWidget(self.startButton, 0, 0, 1, 1)
        
        self.resetButton = QtWidgets.QPushButton(self.groupBox1)
        self.resetButton.setObjectName("resetButton")
        ###
        self.resetButton.setStyleSheet(f'background-color: #555555; font-size: {self.button_text_size}px; color: white;')
        ###
        
        self.gridLayout_6.addWidget(self.resetButton, 0, 1, 1, 1)
        
        self.buttonsLayout.addLayout(self.gridLayout_6)
        
        self.verticalLayout1.addLayout(self.buttonsLayout)
        
        self.gridLayout_4.addWidget(self.groupBox1, 4, 1, 1, 1)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Snapshot 2022-Jan-15 at 11.55.30 AM.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(3)
        self.label.setObjectName("label")
        
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Alvi - Das freundliche, Passauer KI Model"))
        self.label_6.setText(_translate("MainWindow", "Ich schlafe  ..."))
        self.startButton.setText(_translate("MainWindow", "Starte Gespräch"))
        self.resetButton.setText(_translate("MainWindow", "Beende Gespräch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
